version: '3.8'

services:
  postgres:
    image: postgres:15 # image officielle (version 15)
    container_name: postgres # nom du conteneur (facile à référencer)
    restart: unless-stopped # politique de redémarrage
    environment: # variables d'environnement passées au conteneur
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432' # mappe le port du conteneur -> port localhost
    volumes:
      - postgres_data:/var/lib/postgresql/data # volume nommé pour persistance
      - ./db/init:/docker-entrypoint-initdb.d # scripts d'initialisation (optionnel)
    healthcheck: # vérification de santé pour savoir si Postgres est prêt
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '8081:80' # pgAdmin accessible sur http://localhost:8081
    depends_on:
      - postgres
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
